# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.18
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
      - '@openzeppelinupgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.1'

reports:
  exclude_contracts:

